import rospy
from clover import srv
from std_srvs.srv import Trigger
from clover.srv import SetLEDEffect
rospy.init_node('flight')
set_effect = rospy.ServiceProxy('led/set_effect', SetLEDEffect)
get_telemetry = rospy.ServiceProxy('get_telemetry', srv.GetTelemetry)
navigate = rospy.ServiceProxy('navigate', srv.Navigate)
navigate_global = rospy.ServiceProxy('navigate_global', srv.NavigateGlobal)
set_position = rospy.ServiceProxy('set_position', srv.SetPosition)
set_velocity = rospy.ServiceProxy('set_velocity', srv.SetVelocity)
set_attitude = rospy.ServiceProxy('set_attitude', srv.SetAttitude)
set_rates = rospy.ServiceProxy('set_rates', srv.SetRates)
land = rospy.ServiceProxy('land', Trigger)
navigate(x=0, y=0, z=1, frame_id='body', auto_arm=True)
navigate ( x = 1, y = 0 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(7)
navigate ( x = 2, y = 0 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 2.8, y = 0 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 2.8, y = 1 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 2.8, y = 2 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 2.8, y = 3 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 2.8, y = 4 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 2.8, y = 5 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 2, y = 5 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 1, y = 3 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 0, y = 3 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 0, y = 2 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 0, y = 1 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 1, y = 4 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 2, y = 4 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 1, y = 2 , z = 1 , frame_id = 'aruco_map' )
rospy.sleep(8)
navigate ( x = 1.5, y = 1 , z = 1 , frame_id = 'aruco_map' )
land()